language: python
python: 2.7

env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
  #  - TOXENV=py32
   # - TOXENV=py33
  #  - TOXENV=py34
   # - TOXENV=coverage
build:
  ci:
    pre_ci_boot:
      image_name: drydock/u12nodall
      image_tag: prod
      pull: true
      options: '--privileged=true --net=bridge -e FOO=true -e BOO=false'
      
#cache:
 # directories:
  #  - $HOME/.cache/pip
install: pip install docutils tox
#script: tox

